import type { Metadata } from "next";

import { Space_Grotesk } from "next/font/google";
import localFont from 'next/font/local';

import "./globals.css";
import Header from "@/includes/Header";

const satoshi = localFont({
  src: [
    {
      path: "./fonts/Satoshi-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Satoshi-Bold.woff2",
      weight: "700",
      style: "normal",
    }
  ],
  variable: "--font-satoshi",
});

// const satoshi_italic = localFont({
//   src: "./fonts/Satoshi-Italic.woff2",
//   display: "swap",
//   variable: "--font-satoshi-italic",
// });

export const space_grotesk = Space_Grotesk({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-space-grotesk",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${satoshi.className}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
